// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_40KiXMPXqcrdWOz3Ni_X603Iqf2wT1U',
    appId: '1:337956323837:web:cf192499f78f918ece5994',
    messagingSenderId: '337956323837',
    projectId: 'login-equiporobles-780ab',
    authDomain: 'login-equiporobles-780ab.firebaseapp.com',
    storageBucket: 'login-equiporobles-780ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpwnBeLDnDcYq3ZS8aNwAhwG56INZrio',
    appId: '1:337956323837:android:5c9ccfa3088c5f9fce5994',
    messagingSenderId: '337956323837',
    projectId: 'login-equiporobles-780ab',
    storageBucket: 'login-equiporobles-780ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9s3uYzJaagCvZ_-Rb_a07x17suvU-jo',
    appId: '1:337956323837:ios:f6ade4962b751bedce5994',
    messagingSenderId: '337956323837',
    projectId: 'login-equiporobles-780ab',
    storageBucket: 'login-equiporobles-780ab.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9s3uYzJaagCvZ_-Rb_a07x17suvU-jo',
    appId: '1:337956323837:ios:f6ade4962b751bedce5994',
    messagingSenderId: '337956323837',
    projectId: 'login-equiporobles-780ab',
    storageBucket: 'login-equiporobles-780ab.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_40KiXMPXqcrdWOz3Ni_X603Iqf2wT1U',
    appId: '1:337956323837:web:11b919c570abaf08ce5994',
    messagingSenderId: '337956323837',
    projectId: 'login-equiporobles-780ab',
    authDomain: 'login-equiporobles-780ab.firebaseapp.com',
    storageBucket: 'login-equiporobles-780ab.firebasestorage.app',
  );
}
